language: ruby
rvm:
- 2.2.1
env:
  matrix:
  - DB=postgresql
  global:
  - PASSWORD_CONFIRMATION_URL: http://localhost:9000/#/confirm
  - PASSWORD_RESET_URL: http://localhost:9000/#/passwordreset
  - secure: j0h1yFbecv6+V8sPKINPYuIArxJCjC5Zn1JX1fkS32+xVso5QPOo+nQ4IJwOHLFGwJvqzPZbA97bs6GXA7ZfB4wRxf7qBtVWazAyCRy8/2Z9HhmFzbBdnkh8acjm/m8omFNQdC31yFQv2OmsoIvjIAyhHdSMTKtMaZRjFwHjhHY=
  - secure: e2chULnSDPnULwDkU9QvpM4a+1UWnVd6rs0MYXLx+2g8u4RUwdFsNtGJc1yM6zKBxW2AsjZEAtUQzX68wYpXtfg3tElysI2u6erteycWqKiANDaYgw4dGysJEC8+c4DXILHivZ/bNGcsq7VLi74HSLUP2mWRe22lelc2Tix+CG0=
script:
- CODECLIMATE_REPO_TOKEN=fd51d880ee9a35f0efbca53ad39caf7f75aa31280046c52285a59c6b8771fd6a
  bundle exec rake
- bundle exec rspec spec
before_install:
- openssl aes-256-cbc -K $encrypted_e0bf36bc7205_key -iv $encrypted_e0bf36bc7205_iv
  -in callmeishmael_aws.pem.enc -out ~\/.ssh/callmeishmael_aws.pem -d
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test' -U postgres
- bin/rake db:migrate RAILS_ENV=test
addons:
  postgresql: '9.3'
  hosts:
  - travis.dev
deploy:
  provider: heroku
  app: callmeishmael-api
  api_key:
    secure: hkw1yiEtjqYZqDmXaTye4kd3kWNcpq0Xd/8Gc/gyH0rOKSLTtduyf1L4EYeRgtL23TxvRSVcQPdC1CQFA72lvdi+KhHx9n8eIIGJ3vR5jGLAP1Rquo+n1b7D2SACHTSuCZoFii0S2N8yr0jvDHQQksBXp/W12hdSsecMD/RrZZw=
  run:
  - rake db:migrate db:seed
after_success:
  - chmod 600 callmeishmael_aws.pem
  - ssh-add callmeishmael_aws.pem
  - git remote add deploy git@github.com:fishermanswharff/callmeishmael-api.git
  - git push deploy