language: ruby
rvm:
- 2.2.1
env:
  matrix:
  - DB=postgresql
  global:
  - PASSWORD_CONFIRMATION_URL: http://localhost:9000/#/confirm
  - PASSWORD_RESET_URL: http://localhost:9000/#/passwordreset
  - secure: j0h1yFbecv6+V8sPKINPYuIArxJCjC5Zn1JX1fkS32+xVso5QPOo+nQ4IJwOHLFGwJvqzPZbA97bs6GXA7ZfB4wRxf7qBtVWazAyCRy8/2Z9HhmFzbBdnkh8acjm/m8omFNQdC31yFQv2OmsoIvjIAyhHdSMTKtMaZRjFwHjhHY=
  - secure: e2chULnSDPnULwDkU9QvpM4a+1UWnVd6rs0MYXLx+2g8u4RUwdFsNtGJc1yM6zKBxW2AsjZEAtUQzX68wYpXtfg3tElysI2u6erteycWqKiANDaYgw4dGysJEC8+c4DXILHivZ/bNGcsq7VLi74HSLUP2mWRe22lelc2Tix+CG0=
  - secure: eRaD1YZIxTPCRMxlKxwI++bOt6qrcr7bCzGQVfoEwz6p196AchYjL3YOko8QyYm/XvsuptI8iPX1p5xzvWbkRAq3+LEYBBWaRIB311noltQammHz8L8RHbbjoNXJgilEJVjTcisaTlS0eenwDQc8Drm0bg/1N2/eLWcQoYc+OW8=
script:
- bundle exec rspec spec
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test' -U postgres
- bin/rake db:migrate RAILS_ENV=test
addons:
  postgresql: '9.3'
  code_climate:
    secure: jv1VmRhZtmlDqExNRnRw6A/sA0qmesMTp+fJJYHOi8DZnJsWo201ZeN9yuN1Dr1uF/zTe1vgXcf223hErwDLTvxKlpwmqgmEsJMaPiIcdz3xJuU1oaF5yEcWgjhYcQ7PE7YTUagkeILoZSi8WHf62e/GrWo++x3SMrKf5A0pFqk=
  hosts:
  - travis.dev
deploy:
  provider: heroku
  api_key:
    - secure: "iliWUP8ndm1EzyKXVWxq3fT0ec0bz7HE9ZxTIO8WgoVwL8PEV2hXAU+ffaCcXjs/ttNNTEdnFRMiRr7iY6EABNockueh/uw9kM7Lgq2WcHUk0sR9uKlNe+GhEFs1yOY84ybh5KNR/sWLWxFbLBftSozvB+4QRzoU+Dlqyy2hQI0="
  app: callmeishmael-api
  on:
    repo: fishermanswharff/callmeishmael-api
