language: ruby
rvm:
- 2.2.1
env:
  matrix:
  - DB=postgresql
  global:
  - PASSWORD_CONFIRMATION_URL: http://localhost:9000/#/confirm
  - PASSWORD_RESET_URL: http://localhost:9000/#/passwordreset
  - CODE_CLIMATE_TOKEN:
      secure: jv1VmRhZtmlDqExNRnRw6A/sA0qmesMTp+fJJYHOi8DZnJsWo201ZeN9yuN1Dr1uF/zTe1vgXcf223hErwDLTvxKlpwmqgmEsJMaPiIcdz3xJuU1oaF5yEcWgjhYcQ7PE7YTUagkeILoZSi8WHf62e/GrWo++x3SMrKf5A0pFqk=
  - HEROKU_API_KEY:
      secure: cMRgtDQ1oEjC6Pjs4/3m00yVJOy3EPCj0vJ63RSF+24jThNxOtDc2YnKrDM5Nu9SpAGU8FKexyG3P+PmBnM39so3+ysZ64u9syogmBBNX5JLRjaouOETnVrMjiG+/Dg2CKLguS8FRC3XYZg83HrSyMlm1hwWNiCo29RJ/Q7/Pjo=
script:
- bundle exec rspec spec
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test' -U postgres
- bin/rake db:migrate RAILS_ENV=test
addons:
  postgresql: '9.3'
  code_climate:
    repo_token: CODE_CLIMATE_TOKEN
  hosts:
  - travis.dev
deploy:
  provider: heroku
  api_key: HEROKU_API_KEY
  app: callmeishmael-api
